all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    app:
      children:
        appserver:
          hosts:
            178.154.225.116:
    db:
      children:
        dbserver:
          hosts:
            130.193.48.87:
